### ISSUE TITLE
'path-extra' removes some features of node 'path': the non-function properties

### ISSUE THREAD

**Issue by triccardi-systran** [jprichardson/node-path-extra#10]
The non-function properties of node 'path' are not accessible with 'path-extra':

```javascript
var path = require('path');
var path_extra = require('path-extra');
console.log(path.sep, path_extra.sep, path.sep === path_extra.sep);
// prints:
// / undefined false
```

**Comment by jprichardson** [comment]
Fixed.

**Comment by triccardi-systran** [comment]
Other non-function properties from nodejs `path` are missing, like `delimiter`.
Why not importing them all, like it's done for the function properties [here](https://github.com/jprichardson/node-path-extra/blob/c3de85bb82c264bb21e7525c963f59cd0921b0e0/lib/path.js#L6-L10) ?

**Comment by jprichardson** [comment]
Ok, now fixed :p

**Comment by triccardi-systran** [comment]
Thanks!
