### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by RyanZim** [jprichardson/node-path-extra#17]
Would you be open to adding a few more methods?

Some methods I would like to see:

- `.replaceExt()` https://github.com/gulpjs/replace-ext
- `.normalizeTrim()` A `path.normalize()` that trims trailing slashes (needed for comparing paths)
- A method (not sure what to call it) that is a wrapper for   
  `path.basename(filePath, path.extname(filePath))`

Thoughts?

**Comment by RyanZim** [comment]
@jprichardson ping? Would be glad to do PRs.

**Comment by jprichardson** [comment]
Sure, sounds good. Would you mind doing a PR with the latest standard@v8?

**Comment by RyanZim** [comment]
No problem.

I probably will do it in several separate PRs as I get time.

Any ideas on what to call the wrapper for `path.basename(filePath, path.extname(filePath))`?

**Comment by RyanZim** [comment]
> Any ideas on what to call the wrapper for `path.basename(filePath, path.extname(filePath))`?

@jprichardson bump.

**Comment by jprichardson** [comment]
`basenameExcludingExtension()`... although I hate how verbose that is. Or could just create `base()` with an `ext` flag?

**Comment by RyanZim** [comment]
:-1: `basenameExcludingExtension()`

`base()` +  `basename()` = confusion :confused: IMO

Is `file()`, `filename()`, or `name()` too vague?

**Comment by jprichardson** [comment]
It's a bummer, because `basename()` should be `filename()` and our method should be `basename()` :) ... maybe `name()`? I feel like it should have `base` in it since there's no extension.

**Comment by RyanZim** [comment]
`name()` or `base()`; I'll leave the decision to you.

**Comment by jprichardson** [comment]
How do you feel about:

- `base({ ext: true })` === `basename()`
- `base({ ext: false })` === (new functionality)

?

**Comment by RyanZim** [comment]
I would prefer:

- `base(filePath, true)` === `basename()`
- `base(filePath, false)` === (new functionality)

However, that still sort of defeats the purpose of a shortcut (passing two args). Admittedly, `base(filePath, false)` is shorter than `path.basename(filePath, path.extname(filePath))`, but still...

There is no good option IMO.

**Comment by RyanZim** [comment]
@jprichardson *Enough Bikeshedding!* You make a decision and I'll do it as I get time. How's that?

**Comment by jprichardson** [comment]
Ok, your proposal of `base(filePath, boolIncludeExt)` seems good.

**Comment by RyanZim** [comment]
@jprichardson Should it throw an error if `boolIncludeExt` is `undefined`?

**Comment by jprichardson** [comment]
It should default... since we already have `basename()` in node core, maybe the default should be `false`? What are your thoughts?

**Comment by RyanZim** [comment]
> the default should be false

That's the happiest solution! :tada:
