### ISSUE TITLE
Add typings for path-extra

### ISSUE THREAD

**Issue by mike-lischke** [jprichardson/node-path-extra#26]
Please add typings for `path-extra` to the npm registry so that it can be used by Typescript code. `fs-extra` already has this, `path-extra` should do as well.

**Comment by RyanZim** [comment]
Typings are provided by https://github.com/DefinitelyTyped/DefinitelyTyped/. They're not actually maintained by the team. If you'd like typings for `path-extra`, I'd encourage contributing to DefinitelyTyped.

**Comment by mike-lischke** [comment]
Ah, ok :-) Thanks.

**Comment by mike-lischke** [comment]
Btw, you could also switch to Typescript ;-) . The published module would that have .d.ts and .map file already without the need for a separate types module. Just a thought...
